[build-system]
requires = [
    "setuptools_scm>4",
    "setuptools>=52",
    "wheel",
]

[tool.setuptools_scm]


[tool.pytest.ini_options]
addopts = "--benchmark-group-by=func --benchmark-columns=mean,median --benchmark-name=short"
